import { P4grammarListener } from '../antlr_autogenerated/P4grammarListener';
import { StartContext, NameContext } from '../antlr_autogenerated/P4grammarParser';
import { TerminalNode } from 'antlr4ts/tree/TerminalNode';

export class CompletionListener implements P4grammarListener {

	private completionItemList: string[] = new Array<string>();

	constructor(){}

	visitTerminal(nod: TerminalNode): void {}

	enterStart(ctx: StartContext): void {
		this.completionItemList = new Array<string>();
	}

	enterName(ctx: NameContext): void {
		this.completionItemList.push(ctx.getChild(ctx.childCount -1).text);
	}

	get completionList(): string[] {
		return this.completionItemList;
	}
}