import { P4grammarListener } from '../antlr_autogenerated/P4grammarListener';
import { TerminalNode } from 'antlr4ts/tree/TerminalNode';
import { StartContext } from '../antlr_autogenerated/P4grammarParser';

export class HoverListener implements P4grammarListener {
	
	private hoverNodeList: TerminalNode[] = new Array<TerminalNode>();
	private hoverNodeTextList: string[] = new Array<string>();

	constructor(){
		this.hoverNodeList = new Array<TerminalNode>();
		this.hoverNodeTextList = new Array<string>();
	}

	enterStart(ctx: StartContext): void{
		this.hoverNodeList = new Array<TerminalNode>();
		this.hoverNodeTextList = new Array<string>();
	}

	visitTerminal(node: TerminalNode): void{
		this.hoverNodeList.push(node);
		this.hoverNodeTextList.push(node.text);
	}

	get nodeList(): TerminalNode[] {
		return this.hoverNodeList;
	}

	get textList(): string[]{
		return this.hoverNodeTextList;
	}
}