import { TextDocument } from 'vscode-languageserver-textdocument';
import { P4grammarLexer } from '../antlr_autogenerated/P4grammarLexer';
import { CharStreams, CommonTokenStream } from 'antlr4ts';
import { P4grammarParser } from '../antlr_autogenerated/P4grammarParser';
import { ParseTreeWalker } from 'antlr4ts/tree/ParseTreeWalker';
import { HoverListener } from '../listeners/HoverListener';
import { CompletionListener } from '../listeners/CompletionListener';

export let HOVER_LISTENER: HoverListener | null = null;
export let COMPLETION_LISTENER: CompletionListener | null = null;

export function getDataFromAntlr(document: TextDocument) {
	if(HOVER_LISTENER === null){
		HOVER_LISTENER = new HoverListener();
	}

	if(COMPLETION_LISTENER === null){
		COMPLETION_LISTENER = new CompletionListener();
	}

	const lexer = new P4grammarLexer(CharStreams.fromString(document.getText()))
	const token = new CommonTokenStream(lexer);
	const parser = new P4grammarParser(token);

	parser.buildParseTree = true;
	const tree = parser.start();

	ParseTreeWalker.DEFAULT.walk(HOVER_LISTENER, tree);
	ParseTreeWalker.DEFAULT.walk(COMPLETION_LISTENER, tree);
}