import { TextDocument } from 'vscode-languageserver-textdocument';
import { P4grammarLexer } from '../antlr_autogenerated/P4grammarLexer';
import { CharStreams, CommonTokenStream } from 'antlr4ts';
import { P4grammarParser } from '../antlr_autogenerated/P4grammarParser';
import { ParseTreeWalker } from 'antlr4ts/tree/ParseTreeWalker';
import MyListener from './MyListener';
import { P4Server } from '../server';


export function getDataFromAntlr(document: TextDocument) {
	
	const lexer = new P4grammarLexer(CharStreams.fromString(document.uri));
	const token = new CommonTokenStream(lexer);
	const parser = new P4grammarParser(token);

	const tree = parser.program();

	const listener = new MyListener();
	const walker = new ParseTreeWalker();
	walker.walk(listener, tree);

	// return tree
}