import { TerminalNode } from 'antlr4ts/tree/TerminalNode';
import { P4grammarListener } from '../antlr_autogenerated/P4grammarListener';
import { Hover } from 'vscode-languageserver';

export class MyListener implements P4grammarListener {

	private myMap = new Map<string,string>();
	private myList: string[] = new Array<string>();

	constructor(){
		let test: string = "hello world";
		this.myList.push(test);
	}

	getHoverContent(word: string): Hover | undefined {
		let contents = `The word I am pointing at:${word}`;
		// for(let tokens of this.myList){
		// 	if(word === tokens.text){
		// 		contents = tokens.text;
		// 	}
		// }
		console.log(this.myList);
		return {
			contents: contents
		}
	}

	visitTerminal(node: TerminalNode) {
		// console.log(node.payload);
		// console.log(`PAYLOADTEXT: ${node.payload.text}`)
		// console.log(`SYMBOL: ${node.symbol}`)
		// console.log(`GETTEXT: ${node.text}`)
		// let termArray = [];
		// termArray.push(node.text);
		// this.myList = termArray;
		this.myList.push(node.text);
		// console.log(`This is from the visitterminal: ${node.text}`)
	}
}